version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-users
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=users
      - MYSQL_USER=joel
      - MYSQL_PASSWORD=docker
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data: