server:
  port: 8087
  servlet:
    context-path: "/ecomm-user/"

spring:
  application:
    name: ecomm-user-service
  datasource:
    url: jdbc:mysql://localhost:3307/users?useSSL=false&serverTimezone=UTC
    username: joel
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:db/migration,classpath:db/testdb
    enabled: true
    baseline-on-migrate: true


logging:
  level:
    com.joel: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO